### ISSUE TITLE
Integration issue between File Module and HMI Display Module due to C++ and Python

### ISSUE THREAD

**Issue by serb2341** [mag9073/CSCN72030-Sec3-Group1#13]
Problem

Currently, there is an issue establishing communication between the File Module in C++ and the HMI Display Module in Python. 

The original solution to this problem, which was pybind11 or nanobind is not working, and due to the upcoming due date of the assignment, our group has decided to change all of the File Module code that integrates with the HMI Display module to Python. Therefore, the HelpAndRecommendationFile.cpp, Patient.cpp, and File.cpp files, currently written in C++, must be translated into Python.

**Comment by Sudhan-Dahake** [comment]
The File Module has been successfully been converted to python. There is no visible communication issue with HMI and File Module.

**Comment by Sudhan-Dahake** [comment]
The File Module has been successfully been converted to python. There is no visible communication issue with HMI and File Module.
